In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
print('Libraries imported successfully!')

Libraries imported successfully!

In [2]:
df = pd.read_csv('../data/retail_store_inventory.csv')
print('Dataset loaded successfully!')
print('Shape:', df.shape)
df.head()

Dataset loaded successfully!
Shape: (73100, 15)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

## 2. Convert Date and sort the time series

In [3]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(['Store ID', 'Product ID', 'Date']).reset_index(drop=True)
df[['Date', 'Store ID', 'Product ID', 'Units Sold']].head(10)

        Date Store ID Product ID  Units Sold
0 2022-01-01     S001      P0001         127
1 2022-01-02     S001      P0001          81
2 2022-01-03     S001      P0001           5
3 2022-01-04     S001      P0001          58
4 2022-01-05     S001      P0001         147
5 2022-01-06     S001      P0001          37
6 2022-01-07     S001      P0001         107
7 2022-01-08     S001      P0001           2
8 2022-01-09     S001      P0001         350
9 2022-01-10     S001      P0001          36

## 3. Create calendar features

In [4]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Day_of_Week'] = df['Date'].dt.dayofweek
df['Week_of_Year'] = df['Date'].dt.isocalendar().week.astype(int)
df[['Date','Year','Month','Day','Day_of_Week','Week_of_Year']].head(10)

        Date  Year  Month  Day  Day_of_Week  Week_of_Year
0 2022-01-01  2022      1    1            5            52
1 2022-01-02  2022      1    2            6            52
2 2022-01-03  2022      1    3            0             1
3 2022-01-04  2022      1    4            1             1
4 2022-01-05  2022      1    5            2             1
5 2022-01-06  2022      1    6            3             1
6 2022-01-07  2022      1    7            4             1
7 2022-01-08  2022      1    8            5             1
8 2022-01-09  2022      1    9            6             1
9 2022-01-10  2022      1   10            0             2

## 4. Define Store + Product groups

Historical demand must be calculated separately for every Store ID + Product ID combination.

In [5]:
group_cols = ['Store ID', 'Product ID']
print('Store-Product combinations:', df[group_cols].drop_duplicates().shape[0])

Store-Product combinations: 100

## 5. Create lag features

`Lag_1` = previous day, `Lag_7` = 7 days ago, `Lag_14` = 14 days ago, `Lag_28` = 28 days ago.

In [6]:
df['Lag_1'] = df.groupby(group_cols)['Units Sold'].shift(1)
df['Lag_7'] = df.groupby(group_cols)['Units Sold'].shift(7)
df['Lag_14'] = df.groupby(group_cols)['Units Sold'].shift(14)
df['Lag_28'] = df.groupby(group_cols)['Units Sold'].shift(28)
df[['Date','Store ID','Product ID','Units Sold','Lag_1','Lag_7','Lag_14','Lag_28']].head(35)

         Date Store ID Product ID  Units Sold  Lag_1  Lag_7  Lag_14  Lag_28
0  2022-01-01     S001      P0001         127    NaN    NaN     NaN     NaN
1  2022-01-02     S001      P0001          81  127.0    NaN     NaN     NaN
2  2022-01-03     S001      P0001           5   81.0    NaN     NaN     NaN
3  2022-01-04     S001      P0001          58    5.0    NaN     NaN     NaN
4  2022-01-05     S001      P0001         147   58.0    NaN     NaN     NaN
5  2022-01-06     S001      P0001          37  147.0    NaN     NaN     NaN
6  2022-01-07     S001      P0001         107   37.0    NaN     NaN     NaN
7  2022-01-08     S001      P0001           2  107.0  127.0     NaN     NaN
8  2022-01-09     S001      P0001         350    2.0   81.0     NaN     NaN
9  2022-01-10     S001      P0001          36  350.0    5.0     NaN     NaN
10 2022-01-11     S001      P0001          16   36.0   58.0     NaN     NaN
11 2022-01-12     S001      P0001         104   16.0  147.0     NaN     NaN
12 2022-01-13     S001      P0001          80  104.0   37.0     NaN     NaN
13 2022-01-14     S001      P0001         177   80.0  107.0     NaN     NaN
14 2022-01-15     S001      P0001         176  177.0    2.0   127.0     NaN
15 2022-01-16     S001      P0001          97  176.0  350.0    81.0     NaN
16 2022-01-17     S001      P0001          69   97.0   36.0     5.0     NaN
17 2022-01-18     S001      P0001         123   69.0   16.0    58.0     NaN
18 2022-01-19     S001      P0001         211  123.0  104.0   147.0     NaN
19 2022-01-20     S001      P0001          79  211.0   80.0    37.0     NaN
20 2022-01-21     S001      P0001         390   79.0  177.0   107.0     NaN
21 2022-01-22     S001      P0001         191  390.0  176.0     2.0     NaN
22 2022-01-23     S001      P0001          79  191.0   97.0   350.0     NaN
23 2022-01-24     S001      P0001           9   79.0   69.0    36.0     NaN
24 2022-01-25     S001      P0001         189    9.0  123.0    16.0     NaN
25 2022-01-26     S001      P0001          49  189.0  211.0   104.0     NaN
26 2022-01-27     S001      P0001         164   49.0   79.0    80.0     NaN
27 2022-01-28     S001      P0001          97  164.0  390.0   177.0     NaN
28 2022-01-29     S001      P0001          47   97.0  191.0   176.0   127.0
29 2022-01-30     S001      P0001         130   47.0   79.0    97.0    81.0
30 2022-01-31     S001      P0001         200  130.0    9.0    69.0     5.0
31 2022-02-01     S001      P0001         279  200.0  189.0   123.0    58.0
32 2022-02-02     S001      P0001          38  279.0   49.0   211.0   147.0
33 2022-02-03     S001      P0001          71   38.0  164.0    79.0    37.0
34 2022-02-04     S001      P0001          25   71.0   97.0   390.0   107.0

## 6. Create rolling demand features

`shift(1)` prevents the current target from entering its own rolling statistics.

In [7]:
df['Rolling_Mean_7'] = df.groupby(group_cols)['Units Sold'].transform(lambda x: x.shift(1).rolling(7).mean())
df['Rolling_Mean_14'] = df.groupby(group_cols)['Units Sold'].transform(lambda x: x.shift(1).rolling(14).mean())
df['Rolling_Mean_28'] = df.groupby(group_cols)['Units Sold'].transform(lambda x: x.shift(1).rolling(28).mean())
df[['Rolling_Mean_7','Rolling_Mean_14','Rolling_Mean_28']].head(35)

    Rolling_Mean_7  Rolling_Mean_14  Rolling_Mean_28
0              NaN              NaN              NaN
1              NaN              NaN              NaN
2              NaN              NaN              NaN
3              NaN              NaN              NaN
4              NaN              NaN              NaN
5              NaN              NaN              NaN
6              NaN              NaN              NaN
7        80.285714              NaN              NaN
8        62.428571              NaN              NaN
9       100.857143              NaN              NaN
10      105.285714              NaN              NaN
11       99.285714              NaN              NaN
12       93.142857              NaN              NaN
13       99.285714              NaN              NaN
14      109.285714        94.785714              NaN
15      134.142857        98.285714              NaN
16       98.000000        99.428571              NaN
17      102.714286       104.000000              NaN
18      118.000000       108.642857              NaN
19      133.285714       113.214286              NaN
20      133.142857       116.214286              NaN
21      163.571429       136.428571              NaN
22      165.714286       149.928571              NaN
23      163.142857       130.571429              NaN
24      154.571429       128.642857              NaN
25      164.000000       141.000000              NaN
26      140.857143       137.071429              NaN
27      153.000000       143.071429              NaN
28      111.142857       137.357143       116.071429
29       90.571429       128.142857       113.214286
30       97.857143       130.500000       114.964286
31      125.142857       139.857143       121.928571
32      138.000000       151.000000       129.821429
33      136.428571       138.642857       125.928571
34      123.142857       138.071429       127.142857

## 7. Rolling demand volatility

In [8]:
df['Rolling_Std_7'] = df.groupby(group_cols)['Units Sold'].transform(lambda x: x.shift(1).rolling(7).std())
df[['Date','Store ID','Product ID','Units Sold','Rolling_Std_7']].head(35)

         Date Store ID Product ID  Units Sold  Rolling_Std_7
0  2022-01-01     S001      P0001         127            NaN
1  2022-01-02     S001      P0001          81            NaN
2  2022-01-03     S001      P0001           5            NaN
3  2022-01-04     S001      P0001          58            NaN
4  2022-01-05     S001      P0001         147            NaN
5  2022-01-06     S001      P0001          37            NaN
6  2022-01-07     S001      P0001         107            NaN
7  2022-01-08     S001      P0001           2      50.638307
8  2022-01-09     S001      P0001         350      53.384945
9  2022-01-10     S001      P0001          36     121.870736
10 2022-01-11     S001      P0001          16     118.318376
11 2022-01-12     S001      P0001         104     122.119769
12 2022-01-13     S001      P0001          80     120.388854
13 2022-01-14     S001      P0001         177     118.122414
14 2022-01-15     S001      P0001         176     121.790413
15 2022-01-16     S001      P0001          97     113.734235
16 2022-01-17     S001      P0001          69      62.254853
17 2022-01-18     S001      P0001         123      57.872602
18 2022-01-19     S001      P0001         211      43.497126
19 2022-01-20     S001      P0001          79      55.029429
20 2022-01-21     S001      P0001         390      55.191873
21 2022-01-22     S001      P0001         191     112.433472
22 2022-01-23     S001      P0001          79     112.851989
23 2022-01-24     S001      P0001           9     114.865760
24 2022-01-25     S001      P0001         189     124.865070
25 2022-01-26     S001      P0001          49     124.575278
26 2022-01-27     S001      P0001         164     129.345053
27 2022-01-28     S001      P0001          97     126.529311
28 2022-01-29     S001      P0001          47      71.601742
29 2022-01-30     S001      P0001         130      65.237661
30 2022-01-31     S001      P0001         200      66.564326
31 2022-02-01     S001      P0001         279      63.127988
32 2022-02-02     S001      P0001          38      84.011904
33 2022-02-03     S001      P0001          71      86.032663
34 2022-02-04     S001      P0001          25      88.218344

## 8. Competitor price feature

In [9]:
df['Price_Difference'] = df['Price'] - df['Competitor Pricing']
df[['Price','Competitor Pricing','Price_Difference']].head(10)

   Price  Competitor Pricing  Price_Difference
0  33.50               29.69              3.81
1  27.95               30.89             -2.94
2  62.70               58.22              4.48
3  77.88               75.99              1.89
4  28.46               29.40             -0.94
5  91.05               87.30              3.75
6  53.99               58.80             -4.81
7  66.30               63.82              2.48
8  41.72               38.68              3.04
9  32.68               34.71             -2.03

## 9. Review engineered features

In [10]:
feature_columns = ['Date','Store ID','Product ID','Units Sold','Year','Month','Day','Day_of_Week','Week_of_Year','Lag_1','Lag_7','Lag_14','Lag_28','Rolling_Mean_7','Rolling_Mean_14','Rolling_Mean_28','Rolling_Std_7','Price_Difference']
df[feature_columns].head(35)

,Date,Store ID,Product ID,Units Sold,Year,Month,Day,Day_of_Week,Week_of_Year,Lag_1,Lag_7,Lag_14,Lag_28,Rolling_Mean_7,Rolling_Mean_14,Rolling_Mean_28,Rolling_Std_7,Price_Difference
0,2022-01-01,S001,P0001,127,2022,1,1,5,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.81
1,2022-01-02,S001,P0001,81,2022,1,2,6,52,127.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.94
2,2022-01-03,S001,P0001,5,2022,1,3,0,1,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.48
3,2022-01-04,S001,P0001,58,2022,1,4,1,1,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.89
4,2022-01-05,S001,P0001,147,2022,1,5,2,1,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.94
5,2022-01-06,S001,P0001,37,2022,1,6,3,1,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.75
6,2022-01-07,S001,P0001,107,2022,1,7,4,1,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.81
7,2022-01-08,S001,P0001,2,2022,1,8,5,1,107.0,127.0,NaN,NaN,80.285714,NaN,NaN,50.638307,2.48
8,2022-01-09,S001,P0001,350,2022,1,9,6,1,2.0,81.0,NaN,NaN,62.428571,NaN,NaN,53.384945,3.04
9,2022-01-10,S001,P0001,36,2022,1,10,0,2,350.0,5.0,NaN,NaN,100.857143,NaN,NaN,121.870736,-2.03
10,2022-01-11,S001,P0001,16,2022,1,11,1,2,36.0,58.0,NaN,NaN,105.285714,NaN,NaN,118.318376,0.45
11,2022-01-12,S001,P0001,104,2022,1,12,2,2,16.0,147.0,NaN,NaN,99.285714,NaN,NaN,122.119769,-4.67
12,2022-01-13,S001,P0001,80,2022,1,13,3,2,104.0,37.0,NaN,NaN,93.142857,NaN,NaN,120.388854,-4.52
13,2022-01-14,S001,P0001,177,2022,1,14,4,2,80.0,107.0,NaN,NaN,99.285714,NaN,NaN,118.122414,3.00
14,2022-01-15,S001,P0001,176,2022,1,15,5,2,177.0,2.0,127.0,NaN,109.285714,94.785714,NaN,121.790413,-0.16
15,2022-01-16,S001,P0001,97,2022,1,16,6,2,176.0,350.0,81.0,NaN,134.142857,98.285714,NaN,113.734235,3.43
16,2022-01-17,S001,P0001,69,2022,1,17,0,3,97.0,36.0,5.0,NaN,98.000000,99.428571,NaN,62.254853,2.67
17,2022-01-18,S001,P0001,123,2022,1,18,1,3,69.0,16.0,58.0,NaN,102.714286,104.000000,NaN,57.872602,4.19
18,2022-01-19,S001,P0001,211,2022,1,19,2,3,123.0,104.0,147.0,NaN,118.000000,108.642857,NaN,43.497126,2.91
19,2022-01-20,S001,P0001,79,2022,1,20,3,3,211.0,80.0,37.0,NaN,133.285714,113.214286,NaN,55.029429,-1.08
20,2022-01-21,S001,P0001,390,2022,1,21,4,3,79.0,177.0,107.0,NaN,133.142857,116.214286,NaN,55.191873,-2.04
21,2022-01-22,S001,P0001,191,2022,1,22,5,3,390.0,176.0,2.0,NaN,163.571429,136.428571,NaN,112.433472,-3.81
22,2022-01-23,S001,P0001,79,2022,1,23,6,3,191.0,97.0,350.0,NaN,165.714286,149.928571,NaN,112.851989,-2.54
23,2022-01-24,S001,P0001,9,2022,1,24,0,4,79.0,69.0,36.0,NaN,163.142857,130.571429,NaN,114.865760,0.86
24,2022-01-25,S001,P0001,189,2022,1,25,1,4,9.0,123.0,16.0,NaN,154.571429,128.642857,NaN,124.865070,-3.66
25,2022-01-26,S001,P0001,49,2022,1,26,2,4,189.0,211.0,104.0,NaN,164.000000,141.000000,NaN,124.575278,4.03
26,2022-01-27,S001,P0001,164,2022,1,27,3,4,49.0,79.0,80.0,NaN,140.857143,137.071429,NaN,129.345053,-0.99
27,2022-01-28,S001,P0001,97,2022,1,28,4,4,164.0,390.0,177.0,NaN,153.000000,143.071429,NaN,126.529311,3.30
28,2022-01-29,S001,P0001,47,2022,1,29,5,4,97.0,191.0,176.0,127.0,111.142857,137.357143,116.071429,71.601742,-4.78
29,2022-01-30,S001,P0001,130,2022,1,30,6,4,47.0,79.0,97.0,81.0,90.571429,128.142857,113.214286,65.237661,-4.53
30,2022-01-31,S001,P0001,200,2022,1,31,0,5,130.0,9.0,69.0,5.0,97.857143,130.500000,114.964286,66.564326,1.90
31,2022-02-01,S001,P0001,279,2022,2,1,1,5,200.0,189.0,123.0,58.0,125.142857,139.857143,121.928571,63.127988,0.64
32,2022-02-02,S001,P0001,38,2022,2,2,2,5,279.0,49.0,211.0,147.0,138.000000,151.000000,129.821429,84.011904,4.24
33,2022-02-03,S001,P0001,71,2022,2,3,3,5,38.0,164.0,79.0,37.0,136.428571,138.642857,125.928571,86.032663,-1.25
34,2022-02-04,S001,P0001,25,2022,2,4,4,5,71.0,97.0,390.0,107.0,123.142857,138.071429,127.142857,88.218344,4.31

## 10. Check NaNs created by lag/rolling features

NaNs at the beginning of each Store + Product series are expected.

In [11]:
time_series_features = ['Lag_1','Lag_7','Lag_14','Lag_28','Rolling_Mean_7','Rolling_Mean_14','Rolling_Mean_28','Rolling_Std_7']
print(df[time_series_features].isnull().sum())

Lag_1               100
Lag_7               700
Lag_14             1400
Lag_28             2800
Rolling_Mean_7      700
Rolling_Mean_14    1400
Rolling_Mean_28    2800
Rolling_Std_7       700
dtype: int64

## 11. Verify one Store + Product series

In [12]:
sample_series = df[(df['Store ID']=='S001') & (df['Product ID']=='P0001')][['Date','Units Sold','Lag_1','Lag_7','Lag_14','Lag_28','Rolling_Mean_7','Rolling_Mean_14','Rolling_Mean_28']].head(35)
sample_series

,Date,Units Sold,Lag_1,Lag_7,Lag_14,Lag_28,Rolling_Mean_7,Rolling_Mean_14,Rolling_Mean_28
0,2022-01-01,127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-02,81,127.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-03,5,81.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-04,58,5.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-05,147,58.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2022-01-06,37,147.0,NaN,NaN,NaN,NaN,NaN,NaN
6,2022-01-07,107,37.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2022-01-08,2,107.0,127.0,NaN,NaN,80.285714,NaN,NaN
8,2022-01-09,350,2.0,81.0,NaN,NaN,62.428571,NaN,NaN
9,2022-01-10,36,350.0,5.0,NaN,NaN,100.857143,NaN,NaN
10,2022-01-11,16,36.0,58.0,NaN,NaN,105.285714,NaN,NaN
11,2022-01-12,104,16.0,147.0,NaN,NaN,99.285714,NaN,NaN
12,2022-01-13,80,104.0,37.0,NaN,NaN,93.142857,NaN,NaN
13,2022-01-14,177,80.0,107.0,NaN,NaN,99.285714,NaN,NaN
14,2022-01-15,176,177.0,2.0,127.0,NaN,109.285714,94.785714,NaN
15,2022-01-16,97,176.0,350.0,81.0,NaN,134.142857,98.285714,NaN
16,2022-01-17,69,97.0,36.0,5.0,NaN,98.000000,99.428571,NaN
17,2022-01-18,123,69.0,16.0,58.0,NaN,102.714286,104.000000,NaN
18,2022-01-19,211,123.0,104.0,147.0,NaN,118.000000,108.642857,NaN
19,2022-01-20,79,211.0,80.0,37.0,NaN,133.285714,113.214286,NaN
20,2022-01-21,390,79.0,177.0,107.0,NaN,133.142857,116.214286,NaN
21,2022-01-22,191,390.0,176.0,2.0,NaN,163.571429,136.428571,NaN
22,2022-01-23,79,191.0,97.0,350.0,NaN,165.714286,149.928571,NaN
23,2022-01-24,9,79.0,69.0,36.0,NaN,163.142857,130.571429,NaN
24,2022-01-25,189,9.0,123.0,16.0,NaN,154.571429,128.642857,NaN
25,2022-01-26,49,189.0,211.0,104.0,NaN,164.000000,141.000000,NaN
26,2022-01-27,164,49.0,79.0,80.0,NaN,140.857143,137.071429,NaN
27,2022-01-28,97,164.0,390.0,177.0,NaN,153.000000,143.071429,NaN
28,2022-01-29,47,97.0,191.0,176.0,127.0,111.142857,137.357143,116.071429
29,2022-01-30,130,47.0,79.0,97.0,81.0,90.571429,128.142857,113.214286
30,2022-01-31,200,130.0,9.0,69.0,5.0,97.857143,130.500000,114.964286
31,2022-02-01,279,200.0,189.0,123.0,58.0,125.142857,139.857143,121.928571
32,2022-02-02,38,279.0,49.0,211.0,147.0,138.000000,151.000000,129.821429
33,2022-02-03,71,38.0,164.0,79.0,37.0,136.428571,138.642857,125.928571
34,2022-02-04,25,71.0,97.0,390.0,107.0,123.142857,138.071429,127.142857

## Next steps

After verifying these features: remove rows with unavailable lag/rolling values, define `X` and `y`, encode categorical variables, create a chronological train/validation/test split, then train baseline and XGBoost models. Do not use random `train_test_split` for this forecasting task.